In [1]:
from exercises.part2.hungarian_algorithm import *

In [2]:
a = np.random.randint(100, size=(3, 3))

In [3]:
res = hungarian_algorithm(a)
print(f'Optimal matching:\n{res[1]}\n\nValue:\n{np.sum(res[0])}')

Optimal matching:
[[0 0 1]
 [0 1 0]
 [1 0 0]]

Value:
92
